name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: sudo apt-get -y install build-essential libsqlite3-dev libssl-dev
    - name: make
      run: make
