name: histx build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: sudo apt-get -y install build-essential libsqlite3-dev libssl-dev flex bison
    - name: make
      run: make all
    - name: test
      run: ./build/histx-test
